//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vinculacion
    {
        public int idvinculacion { get; set; }
        public string nombre_proyecto { get; set; }
        public Nullable<int> horas { get; set; }
        public string lugar { get; set; }
        public string coordinador { get; set; }
    }
}
